version: "3.8"

services:
  app:
    build:
      context: "."
      target: app
    command: uvicorn main:app --host ${APP_HOST} --port ${APP_PORT}
    env_file:
      - .env
    ports:
      - "${APP_PORT}:${APP_PORT}"
    depends_on:
      - db

  db:
    image: postgres:15.3
    restart: unless-stopped
    volumes:
      - ./var/postgres/data:/var/lib/postgresql/data
      - ./config/postgresql/postgresql.conf:/etc/postgresql/postgresql.conf
      - ./config/postgresql/pg_hba.conf:/etc/postgresql/pg_hba.conf
    env_file:
      - .env
    environment:
      POSTGRES_DB: "${DB_NAME}"
      POSTGRES_USER: "${DB_USERNAME}"
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
    ports:
      - "${DB_PORT}:${DB_PORT}"

  queue:
    image: rabbitmq:3.9.29-management
    restart: unless-stopped
    environment:
      - RABBITMQ_DEFAULT_USER=${MQ_USERNAME}
      - RABBITMQ_DEFAULT_PASS=${MQ_PASSWORD}
    volumes:
      - ./rabbitmq:/var/lib/rabbitmq
    ports:
      - "${MQ_UI_PORT}:${MQ_UI_PORT}"
      - "${MQ_PORT}:${MQ_PORT}"

  celery:
    build:
      context: "."
      target: celery
    command: celery -A core.celery_app worker -l info
    env_file:
      - .env
    depends_on:
      - db
      - queue
